lavalink:
    plugins:
        - dependency: dev.lavalink.youtube:youtube-plugin:1.18.1
          repository: https://maven.lavalink.dev/releases
        - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.8.2
          repository: https://maven.lavalink.dev/releases
        - dependency: com.github.topi314.lavasearch:lavasearch-plugin:1.0.0
          repository: https://maven.lavalink.dev/releases
    server:
        bufferDurationMs: 400
        filters:
            channelMix: true
            distortion: true
            equalizer: true
            karaoke: true
            lowPass: true
            rotation: true
            timescale: true
            tremolo: true
            vibrato: true
            volume: true
        frameBufferDurationMs: 5000
        gcWarnings: true
        opusEncodingQuality: 5
        password: WalksysDev
        playerUpdateInterval: 5
        readTimeout: 60000
        requestTimeout: 60000
        resamplingQuality: HIGH
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: false
            nico: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: false
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
logging:
    file:
        path: ./logs/
    level:
        dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
        lavalink: INFO
        root: INFO
    logback:
        rollingPolicy:
            maxFileSize: 1GB
            maxHistory: 30
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    lavasearch:
        sources:
            - spotify
            - youtube
    lavasrc:
        providers:
            - ytsearch:"%ISRC%"
            - ytsearch:%QUERY%
        sources:
            applemusic: false
            deezer: false
            flowerytts: false
            spotify: true
            yandexmusic: false
            youtube: true
        spotify:
            albumLoadLimit: 10
            clientId: b9a4b5775f1847a2b072573589b530f7
            clientSecret: 682ef411fa5942d28bfe6c409e90f202
            countryCode: US
            localFiles: false
            playlistLoadLimit: 10
            resolveArtistsInSearch: true
    youtube:
        allowDirectPlaylistIds: true
        allowDirectVideoIds: true
        allowSearch: true
        clients:
            - MUSIC
            - WEB
            - TV
            - TVHTML5EMBEDDED
            - ANDROID_VR
        enabled: true
        oauth:
            enabled: true
            refreshToken: null # ركز على الرساله ديت انا فيها بيطلع لي اللينك والكود باخذ التوكن بتاع التي في بتاع حساب جوجل في اليوتيوب بس بيحصل معايا المشكله اللي انا قلت لك عليها في الرساله بس في الصوت بيكون شغال عادي 
            skipInitialization: false # وكمان بفعل ديت بخليهاtrue بعد ما بحط التوكن بعد ما خلاص اخذت التوكن وحطيته وبفعل ديت
        remoteCipher:
            url: https://cipher.kikkia.dev/
            userAgent: lavalink-server
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    http2:
        enabled: false
    port: 5423
